In [164]:
words = open('first_name.txt','r').read().splitlines()

In [165]:

import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt # for making figures
%matplotlib inline

In [166]:
words[:8]

['Aachal',
 'Aadharsh',
 'Aadhavi',
 'Aadhira',
 'Aadidev',
 'Aadil',
 'Aadita',
 'Aaditya']

In [167]:
type(words)

list

In [168]:
len(words)

2195

In [169]:
words = [w.lower() for w in words]

In [170]:
l1 = ''.join(words)

In [171]:
type(l1)

str

In [172]:
l1

'aachalaadharshaadhaviaadhiraaadidevaadilaaditaaadityaaadivaadrikaagneyaahanaahanaaakaaraakankshaaakarshaakashaakeshaakritiaakshiaamraaanchalaanyaaaravaarizaarjayaarnaaarushaarushiaarviaaryaaaryanaashishaashviaasimaasthaaatishaatreyaaayanshaayodaayushaayushiabbasabdulabdurabeerabhayabhayaabhaysinhaabhedhyaabhigyaabhijeetabhijitabhijoyabhikabhilashabhilashaabhimanyuabhinandanabhinavabhishekabhisiktaabhisumatabhithaabhoyabhyudayabinashabrarabuzaracchutanachintyaachyutadarshadhirajadhritadhyanadhyantikaadiladitiadityadityaadvaitaadvaithadvikaadvithadwetaadyaaemanafzanagampreetagrimahadahilanahinsaahmadahnayaijaaishaaishwaryaajaibajaipalajayajeetajitajithakalakankshaakanshaakarshakarshitaakashakhandakhilakhileshakhyaakshatakshayakshayaakshayagunaakshitakshitaalagialanialialimalinaalkaalokamaanamairaamalaamanamaramaraamarnathamarpreetambaramberlieambikaambujamishamishaamitamitaamitavaamiteshamolamrinamritamritaamrutaamruthaamulyaanaanadianakaanandananyaanasanavianchalangadanikaaniketanikris

In [173]:
len(l1)

14187

In [174]:
l1 = l1.lower()
l1

'aachalaadharshaadhaviaadhiraaadidevaadilaaditaaadityaaadivaadrikaagneyaahanaahanaaakaaraakankshaaakarshaakashaakeshaakritiaakshiaamraaanchalaanyaaaravaarizaarjayaarnaaarushaarushiaarviaaryaaaryanaashishaashviaasimaasthaaatishaatreyaaayanshaayodaayushaayushiabbasabdulabdurabeerabhayabhayaabhaysinhaabhedhyaabhigyaabhijeetabhijitabhijoyabhikabhilashabhilashaabhimanyuabhinandanabhinavabhishekabhisiktaabhisumatabhithaabhoyabhyudayabinashabrarabuzaracchutanachintyaachyutadarshadhirajadhritadhyanadhyantikaadiladitiadityadityaadvaitaadvaithadvikaadvithadwetaadyaaemanafzanagampreetagrimahadahilanahinsaahmadahnayaijaaishaaishwaryaajaibajaipalajayajeetajitajithakalakankshaakanshaakarshakarshitaakashakhandakhilakhileshakhyaakshatakshayakshayaakshayagunaakshitakshitaalagialanialialimalinaalkaalokamaanamairaamalaamanamaramaraamarnathamarpreetambaramberlieambikaambujamishamishaamitamitaamitavaamiteshamolamrinamritamritaamrutaamruthaamulyaanaanadianakaanandananyaanasanavianchalangadanikaaniketanikris

In [175]:
s1 = set(l1)
s1

{'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z'}

In [176]:
chars= list(s1)

In [177]:
chars

['s',
 'y',
 'e',
 'g',
 'z',
 'b',
 'q',
 'x',
 't',
 'v',
 'p',
 'k',
 'h',
 'd',
 'j',
 'f',
 'r',
 'c',
 'n',
 'a',
 'w',
 'm',
 'l',
 'i',
 'o',
 'u']

In [178]:
chars = sorted(chars)
chars

['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [179]:
ctoi = {c:i+1 for i,c in enumerate(chars)}

In [180]:
ctoi

{'a': 1,
 'b': 2,
 'c': 3,
 'd': 4,
 'e': 5,
 'f': 6,
 'g': 7,
 'h': 8,
 'i': 9,
 'j': 10,
 'k': 11,
 'l': 12,
 'm': 13,
 'n': 14,
 'o': 15,
 'p': 16,
 'q': 17,
 'r': 18,
 's': 19,
 't': 20,
 'u': 21,
 'v': 22,
 'w': 23,
 'x': 24,
 'y': 25,
 'z': 26}

In [181]:
ctoi['.'] = 0

In [182]:
itoc = {i:c for i,c in ctoi.items()}

In [183]:
itoc

{'a': 1,
 'b': 2,
 'c': 3,
 'd': 4,
 'e': 5,
 'f': 6,
 'g': 7,
 'h': 8,
 'i': 9,
 'j': 10,
 'k': 11,
 'l': 12,
 'm': 13,
 'n': 14,
 'o': 15,
 'p': 16,
 'q': 17,
 'r': 18,
 's': 19,
 't': 20,
 'u': 21,
 'v': 22,
 'w': 23,
 'x': 24,
 'y': 25,
 'z': 26,
 '.': 0}

In [184]:
block_size = 3
X,Y = [],[]
for w in words[:1]:
  context = [0]*block_size
  for ch in w:
    num = ctoi[ch]
    print(context , ch)
    X.append(context)
    Y.append(num)
    context = context[1:] + [num]


[0, 0, 0] a
[0, 0, 1] a
[0, 1, 1] c
[1, 1, 3] h
[1, 3, 8] a
[3, 8, 1] l


In [185]:
X = torch.tensor(X)
Y = torch.tensor(Y)

In [186]:
X.shape

torch.Size([6, 3])

In [187]:
Y.shape

torch.Size([6])

In [188]:
Y # 6 results

tensor([ 1,  1,  3,  8,  1, 12])

In [189]:
X # 6 examples

tensor([[0, 0, 0],
        [0, 0, 1],
        [0, 1, 1],
        [1, 1, 3],
        [1, 3, 8],
        [3, 8, 1]])

In [190]:
C = torch.rand(27,2) # there are 27 letters in total in our vocab and we are trying to represent each letter with 2 numbers

In [191]:
import torch.nn.functional as  f

In [192]:
t = f.one_hot(torch.tensor(4),num_classes = 27) # make 4th 1 rest 0 total 27

In [193]:
t.shape

torch.Size([27])

In [194]:
t

tensor([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0])

In [195]:
t.float()@C # it will give C[4] because all rest are zeros

tensor([0.8092, 0.7888])

In [196]:
C[4]

tensor([0.8092, 0.7888])

In [197]:
X.shape

torch.Size([6, 3])

In [198]:
X

tensor([[0, 0, 0],
        [0, 0, 1],
        [0, 1, 1],
        [1, 1, 3],
        [1, 3, 8],
        [3, 8, 1]])

In [199]:
# C = torch.rand(3,2)
# C

In [200]:
# X = torch.tensor([[0,0,1],
#                   [1,1,2]])
# X
X.shape

torch.Size([6, 3])

In [201]:
# C[X]

In [208]:
C

tensor([[0.4841, 0.7494],
        [0.0740, 0.4971],
        [0.3333, 0.6593],
        [0.5708, 0.0261],
        [0.8092, 0.7888],
        [0.3337, 0.1257],
        [0.7367, 0.1277],
        [0.3446, 0.1937],
        [0.0827, 0.0133],
        [0.8744, 0.7153],
        [0.4417, 0.1660],
        [0.0104, 0.4604],
        [0.6330, 0.4489],
        [0.8964, 0.6734],
        [0.3692, 0.7858],
        [0.3408, 0.3755],
        [0.1030, 0.1031],
        [0.8756, 0.5745],
        [0.5509, 0.1193],
        [0.6813, 0.3071],
        [0.2081, 0.9761],
        [0.0768, 0.2663],
        [0.0854, 0.7363],
        [0.6578, 0.5309],
        [0.4749, 0.4375],
        [0.1668, 0.6594],
        [0.5680, 0.8219]])

In [202]:
C.shape

torch.Size([27, 2])

In [203]:
C[X].shape

torch.Size([6, 3, 2])

In [205]:
embedding = C[X]

In [206]:
embedding

tensor([[[0.4841, 0.7494],
         [0.4841, 0.7494],
         [0.4841, 0.7494]],

        [[0.4841, 0.7494],
         [0.4841, 0.7494],
         [0.0740, 0.4971]],

        [[0.4841, 0.7494],
         [0.0740, 0.4971],
         [0.0740, 0.4971]],

        [[0.0740, 0.4971],
         [0.0740, 0.4971],
         [0.5708, 0.0261]],

        [[0.0740, 0.4971],
         [0.5708, 0.0261],
         [0.0827, 0.0133]],

        [[0.5708, 0.0261],
         [0.0827, 0.0133],
         [0.0740, 0.4971]]])

In [207]:
embedding.shape # so there are 6 examples and each example has 3 letters and then each letter is defined by 2 numbers

torch.Size([6, 3, 2])

In [209]:
#  here lets say a row in X is [1,3,8] these represent 3 letters of the alphabets
# now each letter is deifined by 2 numbers so C[1] means embedding of 'a' and C [3] means embedding of 'c' and so on
# C [X] will replave the [1,3,8] with their respective embeddings

In [218]:
w1 = torch.randn((6,4)) # it means we are having 6 inputs to each neuron and there are 4 neurons
b1 = torch.randn(4)

In [219]:
w1.shape

torch.Size([6, 4])

In [220]:
w1[0]

tensor([-0.6665, -1.5170,  0.7487,  0.4744])

In [225]:
temp = embedding.view(-1,6) # note here it means 0,0,0 0,0,1 0,1,1  1,1,3   1,3,8 and 3 8 1
temp

tensor([[0.4841, 0.7494, 0.4841, 0.7494, 0.4841, 0.7494],
        [0.4841, 0.7494, 0.4841, 0.7494, 0.0740, 0.4971],
        [0.4841, 0.7494, 0.0740, 0.4971, 0.0740, 0.4971],
        [0.0740, 0.4971, 0.0740, 0.4971, 0.5708, 0.0261],
        [0.0740, 0.4971, 0.5708, 0.0261, 0.0827, 0.0133],
        [0.5708, 0.0261, 0.0827, 0.0133, 0.0740, 0.4971]])

In [228]:
temp[3] # it means our third input example  [a,c,h]

tensor([0.0740, 0.4971, 0.0740, 0.4971, 0.5708, 0.0261])

In [230]:
torch.tanh(temp[3]@w1+b1) # it means output of the 4 neurons to out third example

tensor([-0.6768,  0.2148, -0.9577,  0.4209])