In [252]:
text = """India, a land of immense variety and ancient heritage, stands as one of the most culturally rich and diverse nations in the world. Stretching from the snowy peaks of the Himalayas in the north to the tropical coasts of the south, the country’s vast geography mirrors its kaleidoscopic social and cultural landscape. With a civilization that dates back over five millennia, India’s diversity is manifested in its people, languages, religions, traditions, cuisines, art forms, and philosophies. The cultural fabric of India is not a single thread, but a vibrant tapestry woven from multiple strands that coexist harmoniously despite their differences.

At the heart of India’s identity lies its extraordinary diversity. The nation is home to over 1.4 billion people belonging to numerous ethnic groups and speaking more than 1,600 languages and dialects. Hindi and English function as link languages, but each state has its own regional language that reflects ancient linguistic traditions. The Dravidian languages of the south, such as Tamil, Telugu, Kannada, and Malayalam, stand alongside the Indo-Aryan languages of the north, including Hindi, Bengali, Marathi, and Gujarati. Each of these linguistic communities maintains distinct cultural histories, literature, and folk expressions that add depth to India’s cultural mosaic.

Religious diversity is another cornerstone of Indian civilization. India is the birthplace of Hinduism, Buddhism, Jainism, and Sikhism, four of the world’s major religions. It is also home to millions who practice Islam, Christianity, Judaism, Zoroastrianism, and numerous indigenous faiths. This multiplicity of religious traditions has endowed India with a long-standing tradition of tolerance, coexistence, and philosophical dialogue. Temples, mosques, churches, gurudwaras, and monasteries coexist not as symbols of separation but as expressions of a shared quest for spirituality. Festivals such as Diwali, Eid, Christmas, Guru Nanak Jayanti, and Buddha Purnima exemplify this spirit of inclusivity, as people across religious boundaries celebrate together in mutual respect and joy.

The geographical diversity of India further amplifies its cultural richness. The northern plains, nurtured by rivers like the Ganga and Yamuna, cradle ancient centers of civilization such as Varanasi and Delhi. The mountainous Himalayan region preserves unique cultural patterns, from the monastic traditions of Ladakh to the folk dances of Himachal Pradesh. Central India, dotted with tribal communities such as the Gonds, Bhils, and Santhals, retains an organic relationship between people and nature through its rituals, songs, and myths. The western deserts of Rajasthan showcase vibrant attire, royal palaces, and grand folk performances, while the fertile south, surrounded by the Arabian Sea and the Bay of Bengal, displays an artistic finesse evident in temple architecture, classical dance, and sculpture. The northeast, often referred to as the “Seven Sisters,” possesses a remarkable blend of indigenous traditions influenced by Southeast Asian culture, making it one of India’s most distinctive cultural zones.

Indian art, in all its forms, serves as a mirror to its diverse cultural heritage. Classical dance styles such as Bharatanatyam, Kathak, Odissi, Manipuri, Kathakali, Kuchipudi, and Mohiniyattam embody centuries of storytelling, spiritual expression, and rigorous discipline. Each dance form originates from a particular region yet shares the underlying aesthetic principles of grace, rhythm, and devotion. Similarly, Indian classical music, encompassing two major traditions—Hindustani and Carnatic—has evolved through centuries of refinement and spiritual pursuit. In both forms, music is not merely entertainment but a means of connecting with the divine, an idea deeply embedded in Indian philosophy.

Artistic creativity also thrives in India’s folk traditions. Village artisans craft pottery, textiles, jewelry, and woodwork that reflect the colors and textures of rural life. Folk music and dance, such as Bhangra of Punjab, Garba of Gujarat, Bihu of Assam, and Lavani of Maharashtra, capture the local ethos and seasonal rhythms of agrarian communities. These traditions have survived and adapted to modern times, serving as living expressions of India’s collective memory. Indian cinema, particularly Bollywood, stands today as one of the most powerful vehicles of cultural expression, blending music, dance, and drama into an art form that resonates around the globe.

Indian cuisine also tells a story of cultural diversity. Each region of the country presents its own palette of flavors shaped by geography, climate, and tradition. Northern India is known for its rich gravies, breads, and use of dairy products, while southern India delights in rice-based dishes, coconut, and spices. The western coast features seafood and tangy curries influenced by colonial encounters and maritime trade. The eastern states bring subtle sweetness and fish-based delicacies that highlight their connection with rivers and deltas. Spices, herbs, and regional ingredients not only define Indian food but also represent centuries of cultural exchange, trade, and adaptation. Across the country, cooking remains intertwined with rituals, festivals, and hospitality—a sacred act that celebrates both community and individuality.

Indian architecture stands as a material testimony to its diverse cultural evolution. The ancient rock-cut caves of Ajanta and Ellora, the majestic temples of Khajuraho and Konark, the grand forts of Rajasthan, and the Mughal masterpieces like the Taj Mahal all capture different epochs of Indian artistry and history. Each monument reflects a synthesis of influences—Hindu, Islamic, Persian, Buddhist, and European—integrated into a style uniquely Indian. In modern India, this architectural legacy continues through innovative blends of tradition and modernity, visible in urban skylines as well as rural dwellings that balance function with aesthetic grace.

Philosophical diversity has played a powerful role in shaping the Indian psyche. From the ancient Vedic hymns to the teachings of Buddha and Mahavira, from the philosophical treatises of Adi Shankaracharya to the reform movements led by figures like Swami Vivekananda and Mahatma Gandhi, Indian thought has constantly evolved through dialogue and introspection. Concepts such as karma, dharma, and ahimsa (non-violence) have not only defined personal ethics but also influenced global philosophical discourse. The coexistence of material and spiritual pursuits remains a hallmark of Indian civilization, inspiring a worldview that values both the inner and outer dimensions of life.

Despite its vast differences, the unifying thread of Indian culture lies in its philosophy of unity in diversity. India’s diversity has rarely been a source of permanent division; rather, it has been a source of strength and creativity. The Indian Constitution itself recognizes and respects this pluralism by protecting linguistic, religious, and cultural freedoms. The spirit of democracy further reinforces the idea that every voice, regardless of caste, creed, or region, contributes to the national identity. This inclusive ethos ensures that diversity does not lead to fragmentation but to a shared sense of purpose and belonging.

In the contemporary world, where globalization often threatens to homogenize cultures, India continues to preserve its diversity while engaging with modernity. Urbanization, technological growth, and migration have undoubtedly transformed traditional lifestyles, but they have also created new forms of cultural expression. Indian youth, while rooted in their heritage, are increasingly global in outlook, bridging ancient traditions with modern aspirations. Literary works, films, and digital art platforms now serve as spaces where old and new, local and global, coexist seamlessly.

In conclusion, India’s diversity and culture form the living essence of its civilization. The country’s ability to balance continuity with change, individuality with unity, and spirituality with material progress is what makes it unique. India’s cultural wealth cannot be measured by monuments or festivals alone; it lives in the everyday life of its people, in their languages, faiths, creativity, and compassion. As India moves forward into the future, this spirit of diversity—rooted in harmony and respect—remains its greatest strength and its most enduring gift to the world. """

In [253]:
l1 = text.split()

In [254]:
l1

['India,',
 'a',
 'land',
 'of',
 'immense',
 'variety',
 'and',
 'ancient',
 'heritage,',
 'stands',
 'as',
 'one',
 'of',
 'the',
 'most',
 'culturally',
 'rich',
 'and',
 'diverse',
 'nations',
 'in',
 'the',
 'world.',
 'Stretching',
 'from',
 'the',
 'snowy',
 'peaks',
 'of',
 'the',
 'Himalayas',
 'in',
 'the',
 'north',
 'to',
 'the',
 'tropical',
 'coasts',
 'of',
 'the',
 'south,',
 'the',
 'country’s',
 'vast',
 'geography',
 'mirrors',
 'its',
 'kaleidoscopic',
 'social',
 'and',
 'cultural',
 'landscape.',
 'With',
 'a',
 'civilization',
 'that',
 'dates',
 'back',
 'over',
 'five',
 'millennia,',
 'India’s',
 'diversity',
 'is',
 'manifested',
 'in',
 'its',
 'people,',
 'languages,',
 'religions,',
 'traditions,',
 'cuisines,',
 'art',
 'forms,',
 'and',
 'philosophies.',
 'The',
 'cultural',
 'fabric',
 'of',
 'India',
 'is',
 'not',
 'a',
 'single',
 'thread,',
 'but',
 'a',
 'vibrant',
 'tapestry',
 'woven',
 'from',
 'multiple',
 'strands',
 'that',
 'coexist',
 'harm

In [255]:
words_list = list(l1)

In [256]:
words_list = [w for w in words_list if w.isalpha()]

In [257]:
s1 = set(words_list)

In [258]:
len(s1)

467

In [259]:
s1

{'Across',
 'Adi',
 'Ajanta',
 'Arabian',
 'Artistic',
 'As',
 'Asian',
 'At',
 'Bay',
 'Bhangra',
 'Bihu',
 'Buddha',
 'Central',
 'Classical',
 'Concepts',
 'Constitution',
 'Despite',
 'Dravidian',
 'Each',
 'English',
 'Festivals',
 'Folk',
 'From',
 'Ganga',
 'Garba',
 'Guru',
 'Himachal',
 'Himalayan',
 'Himalayas',
 'Hindi',
 'In',
 'India',
 'Indian',
 'It',
 'Khajuraho',
 'Ladakh',
 'Lavani',
 'Literary',
 'Mahal',
 'Mahatma',
 'Mohiniyattam',
 'Mughal',
 'Nanak',
 'Northern',
 'Philosophical',
 'Purnima',
 'Rajasthan',
 'Religious',
 'Sea',
 'Shankaracharya',
 'Southeast',
 'Stretching',
 'Swami',
 'Taj',
 'The',
 'These',
 'This',
 'Varanasi',
 'Vedic',
 'Village',
 'Vivekananda',
 'With',
 'a',
 'ability',
 'across',
 'act',
 'adapted',
 'add',
 'aesthetic',
 'agrarian',
 'ahimsa',
 'all',
 'alongside',
 'also',
 'amplifies',
 'an',
 'ancient',
 'and',
 'another',
 'architectural',
 'architecture',
 'are',
 'around',
 'art',
 'artisans',
 'artistic',
 'artistry',
 'as',
 'b

In [260]:
words = list(s1)

In [261]:
words[:4]

['cornerstone', 'Hindi', 'alongside', 'preserves']

In [262]:
words = sorted(words)

In [263]:
words[:5]

['Across', 'Adi', 'Ajanta', 'Arabian', 'Artistic']

In [268]:
len(words)

467

In [270]:
wtoi = {w:i+1 for i,w in enumerate(words)}

In [271]:
wtoi['.'] = 0

In [272]:
itow = {i:w for i,w in wtoi.items() }

In [273]:
wtoi

{'Across': 1,
 'Adi': 2,
 'Ajanta': 3,
 'Arabian': 4,
 'Artistic': 5,
 'As': 6,
 'Asian': 7,
 'At': 8,
 'Bay': 9,
 'Bhangra': 10,
 'Bihu': 11,
 'Buddha': 12,
 'Central': 13,
 'Classical': 14,
 'Concepts': 15,
 'Constitution': 16,
 'Despite': 17,
 'Dravidian': 18,
 'Each': 19,
 'English': 20,
 'Festivals': 21,
 'Folk': 22,
 'From': 23,
 'Ganga': 24,
 'Garba': 25,
 'Guru': 26,
 'Himachal': 27,
 'Himalayan': 28,
 'Himalayas': 29,
 'Hindi': 30,
 'In': 31,
 'India': 32,
 'Indian': 33,
 'It': 34,
 'Khajuraho': 35,
 'Ladakh': 36,
 'Lavani': 37,
 'Literary': 38,
 'Mahal': 39,
 'Mahatma': 40,
 'Mohiniyattam': 41,
 'Mughal': 42,
 'Nanak': 43,
 'Northern': 44,
 'Philosophical': 45,
 'Purnima': 46,
 'Rajasthan': 47,
 'Religious': 48,
 'Sea': 49,
 'Shankaracharya': 50,
 'Southeast': 51,
 'Stretching': 52,
 'Swami': 53,
 'Taj': 54,
 'The': 55,
 'These': 56,
 'This': 57,
 'Varanasi': 58,
 'Vedic': 59,
 'Village': 60,
 'Vivekananda': 61,
 'With': 62,
 'a': 63,
 'ability': 64,
 'across': 65,
 'act': 66

In [275]:
words_list

['a',
 'land',
 'of',
 'immense',
 'variety',
 'and',
 'ancient',
 'stands',
 'as',
 'one',
 'of',
 'the',
 'most',
 'culturally',
 'rich',
 'and',
 'diverse',
 'nations',
 'in',
 'the',
 'Stretching',
 'from',
 'the',
 'snowy',
 'peaks',
 'of',
 'the',
 'Himalayas',
 'in',
 'the',
 'north',
 'to',
 'the',
 'tropical',
 'coasts',
 'of',
 'the',
 'the',
 'vast',
 'geography',
 'mirrors',
 'its',
 'kaleidoscopic',
 'social',
 'and',
 'cultural',
 'With',
 'a',
 'civilization',
 'that',
 'dates',
 'back',
 'over',
 'five',
 'diversity',
 'is',
 'manifested',
 'in',
 'its',
 'art',
 'and',
 'The',
 'cultural',
 'fabric',
 'of',
 'India',
 'is',
 'not',
 'a',
 'single',
 'but',
 'a',
 'vibrant',
 'tapestry',
 'woven',
 'from',
 'multiple',
 'strands',
 'that',
 'coexist',
 'harmoniously',
 'despite',
 'their',
 'At',
 'the',
 'heart',
 'of',
 'identity',
 'lies',
 'its',
 'extraordinary',
 'The',
 'nation',
 'is',
 'home',
 'to',
 'over',
 'billion',
 'people',
 'belonging',
 'to',
 'numero

In [277]:
words_context = 3
X,Y = [], []
context = [0] * words_context
for w in words_list[:5]:

  index = wtoi[w]
  print(context,index)
  X.append(context)
  Y.append(index)
  context = context[1:] + [index]


[0, 0, 0] 63
[0, 0, 63] 252
[0, 63, 252] 307
[63, 252, 307] 232
[252, 307, 232] 451


In [278]:
X

[[0, 0, 0], [0, 0, 63], [0, 63, 252], [63, 252, 307], [252, 307, 232]]

In [279]:
Y

[63, 252, 307, 232, 451]

In [280]:
import torch
X = torch.tensor(X)
Y = torch.tensor(Y)


In [281]:
X.shape # so we have taken 5 exampples and each example has 3 words

torch.Size([5, 3])

In [283]:
Y.shape

torch.Size([5])

In [284]:
len(wtoi)

468

In [285]:
total_words = len(wtoi)
embedding_size = 2
C = torch.rand(total_words,embedding_size)

In [286]:
X.shape

torch.Size([5, 3])

In [287]:
X

tensor([[  0,   0,   0],
        [  0,   0,  63],
        [  0,  63, 252],
        [ 63, 252, 307],
        [252, 307, 232]])

In [288]:
embeddings = C[X]

In [289]:
embeddings

tensor([[[0.2372, 0.8868],
         [0.2372, 0.8868],
         [0.2372, 0.8868]],

        [[0.2372, 0.8868],
         [0.2372, 0.8868],
         [0.8494, 0.0994]],

        [[0.2372, 0.8868],
         [0.8494, 0.0994],
         [0.0076, 0.5505]],

        [[0.8494, 0.0994],
         [0.0076, 0.5505],
         [0.2093, 0.8040]],

        [[0.0076, 0.5505],
         [0.2093, 0.8040],
         [0.5278, 0.2541]]])

In [290]:
embeddings.shape # it means we have 5 examples each example has 3 words and each word is represented by 2 numbers

torch.Size([5, 3, 2])

In [293]:
neuron_in_first_layer = 10
w1 = torch.randn((words_context*embedding_size,neuron_in_first_layer))

In [294]:
b1 = torch.randn(neuron_in_first_layer)

In [295]:
temp = embeddings.view(-1,embedding_size*words_context)

In [296]:
temp

tensor([[0.2372, 0.8868, 0.2372, 0.8868, 0.2372, 0.8868],
        [0.2372, 0.8868, 0.2372, 0.8868, 0.8494, 0.0994],
        [0.2372, 0.8868, 0.8494, 0.0994, 0.0076, 0.5505],
        [0.8494, 0.0994, 0.0076, 0.5505, 0.2093, 0.8040],
        [0.0076, 0.5505, 0.2093, 0.8040, 0.5278, 0.2541]])

In [297]:
temp[3] # we ahve 3 words in our example and there are 2 numbers for each word

tensor([0.8494, 0.0994, 0.0076, 0.5505, 0.2093, 0.8040])

In [299]:
torch.tanh(temp[3]@w1+b1) # it means output of the 10 neurons to out third example

tensor([ 0.9019,  0.1071,  0.2949,  0.9702,  0.9697,  0.7306, -0.9908, -0.6323,
        -0.6670, -0.1244])

In [300]:

h = torch.tanh(emb.view(-1,embedding_size*words_context)@w1+b1)

In [301]:
w2 = torch.randn(neuron_in_first_layer,total_words)
b2 = torch.randn(total_words)

In [302]:

logits = h@w2+b2

In [303]:

counts = logits.exp()
probs = counts / counts.sum(1,keepdims = True)

In [305]:
probs.shape

torch.Size([8, 468])

In [306]:
Y.shape

torch.Size([5])

In [307]:

loss = -probs[torch.arange(5),Y].log().mean()
loss

tensor(9.1620, grad_fn=<NegBackward0>)